TOPLEVEL_LANG = verilog
VERILOG_SOURCES = sources/picorv32.v
TOPLEVEL = picorv32
MODULE = test_picorv32

COMPILE_ARGS=-D DEBUGNETS=1

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
